// <auto-generated />
namespace EFExamples2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class _4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4));
        
        string IMigrationMetadata.Id
        {
            get { return "202011222320377_4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
